### ISSUE TITLE
Build broken by 634c1dcb1714e24f6fa24ef2584e7c8d3bf7fc5e

### ISSUE THREAD

**Issue by uglym8** [mozilla/rr#1683]
/tmp/tmp_rr_build/rr/obj/32/ptrace_debug_regs.c:7:13: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
    static void breakpoint() {}
                  ^
fix is trivial: just add void to function declaration:
```C
static void breakpoint(void) {}
```
instead of
```C
static void breakpoint() {}
```
in C int func() and int func(void) are not the same thing. The former accepts  an arbitrary number of arguments while the latter accepts none.

**Comment by rocallahan** [comment]
Thanks!
