### ISSUE TITLE
i386: build failure

### ISSUE THREAD

**Issue by bernhardu** [mozilla/rr#2705]
Following failure seems to got introduced in 9b8adb190680.
```
[ 34%] Building CXX object CMakeFiles/rr.dir/src/util.cc.o
/home/benutzer/rr/src/util.cc: Assembler messages:
/home/benutzer/rr/src/util.cc:1072: Error: `xsave64' is only supported in 64-bit mode
make[2]: *** [CMakeFiles/rr.dir/build.make:999: CMakeFiles/rr.dir/src/util.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6567: CMakeFiles/rr.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```
I tried to get it compile by following, but I am unsure if that is right:
```
diff --git a/src/util.cc b/src/util.cc
index 645c267a..e52f2f9f 100644
--- a/src/util.cc
+++ b/src/util.cc
@@ -1069,7 +1069,11 @@ bool cpu_has_xsave_fip_fdp_quirk() {
   xsave_buf[1] = 0;
   asm volatile("finit\n"
                "fld1\n"
+#if defined(__x86_64__)
                "xsave64 %0\n"
+#else
+               "xsave %0\n"
+#endif
                : "=m"(xsave_buf)
                : "a"(1), "d"(0)
                : "memory");
```
A build with that change could run the tests like this, inside a qemu VM on an Intel cpu:
```
99% tests passed, 6 tests failed out of 1249

Total Test time (real) = 1847.28 sec

The following tests FAILED:
        920 - nested_detach_wait (Failed)
        921 - nested_detach_wait-no-syscallbuf (Failed)
        1144 - nested_detach (Failed)
        1145 - nested_detach-no-syscallbuf (Failed)
        1156 - record_replay (Timeout)
        1157 - record_replay-no-syscallbuf (Timeout)
```

**Comment by rocallahan** [comment]
I pushed your fix. Thanks.

Those test failures are unfortunately not really worth my time debugging. Feel free to dig into them if you want. They shouldn't affect rr usage in practice.

**Comment by bernhardu** [comment]
Thank you very much for fixing.
For the nested_detach tests exists #2605, but yes, I understand that i386 is no priority nowadays.
