### ISSUE TITLE
Compilation encountering overflow

### ISSUE THREAD

**Issue by johnfxgalea** [mozilla/rr#2368]
I am trying to compile from source and am hitting a compilation error. I'm following the build instructions from [here](https://github.com/mozilla/rr/wiki/Building-And-Installing).

Due to my current use-case, I am working on a i686 Ubuntu (Linux) 14.04 LTS system.

```
/home/john/rr/src/AddressSpace.cc: In function ‘rr::MemoryRange rr::choose_global_exclusion_range()’:
/home/john/rr/src/AddressSpace.cc:1887:38: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
   return MemoryRange(addr, range_size);
                                      ^
/home/john/rr/src/AddressSpace.cc: In member function ‘rr::remote_ptr<void> rr::AddressSpace::chaos_mode_find_free_memory(rr::RecordTask*, size_t)’:
/home/john/rr/src/AddressSpace.cc:1952:62: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
                               remote_ptr<void>(0x10007fff8000));
                                                              ^
/home/john/rr/src/AddressSpace.cc:1953:74: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
       MemoryRange asan_allocator_reserved(remote_ptr<void>(0x600000000000),
                                                                          ^
/home/john/rr/src/AddressSpace.cc:1954:74: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
                                           remote_ptr<void>(0x640000000000));
```

Sorry if I missed something!

**Comment by rocallahan** [comment]
OK try https://github.com/mozilla/rr/commit/54167b640870601566fb928808ecd3c71d3858f7

**Comment by johnfxgalea** [comment]
Thanks for the quick response! 

Im still getting the following:

```
/home/john/rr/src/AddressSpace.cc: In function ‘rr::MemoryRange rr::choose_global_exclusion_range()’:
/home/john/rr/src/AddressSpace.cc:1887:38: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
   return MemoryRange(addr, range_size);
```

**Comment by rocallahan** [comment]
Try https://github.com/mozilla/rr/commit/9d73b4d8791586e6d1036d0d44d252041236588f ?

If there are more you could try fixing them locally and sending us a PR :-)

**Comment by johnfxgalea** [comment]
Thanks, it works now!
