### ISSUE TITLE
sysctl() is deprecated and may break build with glibc >= 2.30

### ISSUE THREAD

**Issue by ddcc** [mozilla/rr#2392]
As of glibc 2.30 (https://savannah.gnu.org/forum/forum.php?forum_id=9515), and recent version of Linux (http://patches-tcwg.linaro.org/patch/19443/), the sysctl() system call and its header file sysctl.h are deprecated and to be removed. This breaks the default build, since warnings are treated as errors.

```
In file included from /home/ddcc/rr/src/test/sysctl.c:4:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
/home/ddcc/rr/src/test/sysctl.c: In function ‘main’:
/home/ddcc/rr/src/test/sysctl.c:13:3: error: ‘sysctl’ is deprecated [-Werror=deprecated-declarations]
   13 |   if (sysctl(name, 2, &sig_max, &len, NULL, 0) == -1) {
```

Locally, I removed support for sysctl (https://github.com/ddcc/rr/commit/28bdc5611f7a675127926f78adeb0d1c3eb12570), but the correct fix would probably be to re-define the symbols in a local header file until they are actually removed.

**Comment by khuey** [comment]
We should probably switch to <linux/syscall.h>

**Comment by rocallahan** [comment]
We will need to make the call using `syscall()` and `RR_sysctl`.
