### ISSUE TITLE
Does not compile with gcc-7.2

### ISSUE THREAD

**Issue by huangyihe** [mozilla/rr#2162]
I'm getting the following compile error when building `rr` with gcc/g++ version 7.2.0:

```text
[ 51%] Building CXX object CMakeFiles/rr.dir/src/TraceStream.cc.o
In file included from /usr/include/capnp/message.h:26:0,
                 from /home/yihehuang/git/rr/src/TraceStream.cc:5:
/usr/include/capnp/layout.h:129:65: error: could not convert template argument ‘b’ from ‘bool’ to ‘capnp::Kind’
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                 ^
/usr/include/capnp/layout.h:129:66: error: template argument 1 is invalid
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                  ^~
CMakeFiles/rr.dir/build.make:1501: recipe for target 'CMakeFiles/rr.dir/src/TraceStream.cc.o' failed
```

Compilation only fails if I use gcc version 7. If I use the default gcc 5.4 that comes with Ubuntu 16.04 then it works fine. I use Ubuntu 16.04 and the gcc-7 package from [here](https://launchpad.net/~jonathonf/+archive/ubuntu/gcc-7.2?field.series_filter=xenial).

**Comment by rocallahan** [comment]
Strange, it compiles fine with gcc 7.2.1 for me. I suspect it's an incompatibility between gcc 7.2.0 and the version of capnp you have installed. You could try building an up-to-date capnp package.

**Comment by huangyihe** [comment]
Yeah, apparently the capnp package from the Ubuntu package manager is too old for gcc 7. Had to compile and install capnp from source to make it work.
